name: washington_dc
system_name: washington_dc_bikeshare
source_url: "https://capitalbikeshare.com/system-data"
s3_bucket: s3://capitalbikeshare-data

aws_sync: true
file_matcher:
  - capitalbikeshare-tripdata
renamed_columns:
  ride_id: id
  rideable_type: rideable_type
  started_at: start_time
  ended_at: end_time
  start_station_name: start_station_name
  start_station_id: start_station_id
  end_station_name: end_station_name
  end_station_id: end_station_id
  start_lat: start_station_latitude
  start_lng: start_station_longitude
  end_lat: end_station_latitude
  end_lng: end_station_longitude
  member_casual: member_casual

  Duration: duration
  Start date: start_time
  End date: end_time
  Start station number: start_station_id
  Start station: start_station_name
  End station number: end_station_id
  End station: end_station_name
  Bike number: bike_number
  Member type: member_type
date_formats:
  - "%Y-%m-%d %H:%M:%S"
processing_pipeline:
  - rename_columns
  - convert_to_datetime
  - select_final_columns
