from __future__ import annotations

from pathlib import Path
from typing import Any, Dict, List

import yaml
from tabulate import tabulate


TABLE_TEMPLATE = """# Supported cities

Generated from `src/citybikeshare/config/cities/`. Use the **CLI name** with commands like `poetry run citybikeshare pipeline <cli_name>`.

{table}

_This file is generated by `scripts/generate_cities_table.py`. Do not edit it by hand._
"""


def load_city_configs(config_dir: Path) -> List[Dict[str, Any]]:
    """Load all city configs from YAML files in config_dir."""
    configs: List[Dict[str, Any]] = []

    for yaml_path in sorted(config_dir.glob("*.yaml")):
        data = yaml.safe_load(yaml_path.read_text()) or {}

        cli_name = yaml_path.stem
        city_name = data.get("name") or cli_name.replace("_", " ").title()
        source_url = data.get("source_url", "")
        aws_sync = bool(data.get("aws_sync", False))

        configs.append(
            {
                "cli_name": cli_name,
                "city_name": city_name,
                "source_url": source_url,
                "sync": "AWS S3" if aws_sync else "Custom",
            }
        )

    # Sort by human-readable city name for stable output
    configs.sort(key=lambda c: c["city_name"].lower())
    return configs


def generate_markdown(configs: List[Dict[str, Any]]) -> str:
    """Generate the supported_cities markdown content."""
    rows: List[Dict[str, str]] = []
    for cfg in configs:
        source_url = cfg["source_url"] or ""
        source_cell = f"[link]({source_url})" if source_url else ""
        rows.append(
            {
                "City": cfg["city_name"],
                "CLI name": f"`{cfg['cli_name']}`",
                "Source": source_cell,
                "Sync": cfg["sync"],
            }
        )

    table = tabulate(rows, headers="keys", tablefmt="github")
    return TABLE_TEMPLATE.format(table=table)


def main() -> None:
    repo_root = Path(__file__).resolve().parent.parent
    config_dir = repo_root / "src" / "citybikeshare" / "config" / "cities"

    if not config_dir.is_dir():
        raise SystemExit(f"Config directory not found: {config_dir}")

    configs = load_city_configs(config_dir)

    doc_dir = repo_root / "doc"
    doc_dir.mkdir(parents=True, exist_ok=True)
    output_path = doc_dir / "supported_cities.md"

    markdown = generate_markdown(configs)
    output_path.write_text(markdown, encoding="utf-8")


if __name__ == "__main__":
    main()

