"""Inventory raw column names and sample values for a city.

Goal: surface every column that appears in a city's raw/ files (across schema
eras), grouped by the commonized name it maps to, together with a handful of
sample values per raw column. This makes it easy to decide which additional
columns are worth carrying into the parquet and which raw variants across
cities encode the same concept (so they can share one output column name).

Usage:
    poetry run python scripts/inventory_raw_columns.py boston
    poetry run python scripts/inventory_raw_columns.py boston --rows 200 --distinct 40
"""

import argparse
import csv
import gzip
import io
import os
from collections import OrderedDict

from citybikeshare.config.loader import load_city_config
from citybikeshare.etl.transform import filter_filenames
from citybikeshare.utils.paths import get_csv_files

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def open_text(path):
    """Open a raw file transparently whether gzipped or plain."""
    if path.endswith(".gz"):
        return io.TextIOWrapper(gzip.open(path, "rb"), encoding="utf-8", errors="replace")
    return open(path, "rt", encoding="utf-8", errors="replace")


def read_header(path):
    """Return just the header row of a raw file (no value sampling)."""
    header, _ = sample_file(path, 0, 0)
    return header


def sample_file(path, max_rows, max_distinct):
    """Return (header, {column: OrderedDict of distinct sample values}) for one file."""
    with open_text(path) as fh:
        reader = csv.reader(fh)
        try:
            header = next(reader)
        except StopIteration:
            return [], {}
        header = [h.strip() for h in header]
        samples = {col: OrderedDict() for col in header}
        for i, row in enumerate(reader):
            if i >= max_rows:
                break
            for col, val in zip(header, row):
                val = val.strip()
                if val == "":
                    continue
                bucket = samples[col]
                if val not in bucket and len(bucket) < max_distinct:
                    bucket[val] = None
        return header, samples


def build_inventory(city, max_rows, max_distinct):
    config = load_city_config(city)
    renamed = config.get("renamed_columns", {}) or {}
    final_cols = config.get("final_columns", []) or []

    raw_dir = os.path.join(REPO_ROOT, "data", city, "raw")
    all_files = sorted(get_csv_files(raw_dir))
    # Use the pipeline's own filter so "feeds the pipeline" is identical to transform —
    # it honors both file_matcher AND excluded_filenames (e.g. NYC's duplicate 2018 files).
    matched_files = set(filter_filenames(all_files, config))

    # column -> {"files": [basenames], "values": OrderedDict}. Only columns from
    # pipeline-fed files land here; ignored files (station rosters, etc.) are listed
    # separately so their columns don't pollute the "what to add" analysis.
    columns = OrderedDict()
    ignored_files = []

    for path in all_files:
        basename = os.path.basename(path)
        if path not in matched_files:
            ignored_files.append((basename, read_header(path)))
            continue
        header, samples = sample_file(path, max_rows, max_distinct)
        for col in header:
            entry = columns.setdefault(col, {"files": [], "values": OrderedDict()})
            entry["files"].append(basename)
            for val in samples.get(col, {}):
                if val not in entry["values"] and len(entry["values"]) < max_distinct:
                    entry["values"][val] = None

    return config, columns, renamed, final_cols, ignored_files, all_files, matched_files


def commonized_name(col, renamed):
    return renamed.get(col, "")


def render_markdown(
    city, config, columns, renamed, final_cols, ignored_files, all_files, matched_files
):
    lines = []
    lines.append(f"# Raw column inventory — {city}")
    lines.append("")
    lines.append(
        "Auto-generated by `scripts/inventory_raw_columns.py`. Columns are drawn only from "
        "files that feed the pipeline (per `filter_filenames`); station rosters and other "
        "ignored files are listed at the end, not mixed into the column analysis. Each column "
        "shows the commonized name it maps to via `renamed_columns` and sample distinct values."
    )
    lines.append("")
    lines.append(f"- Raw files in `data/{city}/raw/`: **{len(all_files)}**")
    lines.append(f"- Files feeding the pipeline: **{len(matched_files)}**")
    lines.append(f"- Distinct raw column names (pipeline-fed): **{len(columns)}**")
    lines.append(f"- `file_matcher`: `{config.get('file_matcher')}`")
    lines.append("")

    # Group raw columns by the commonized target so shared concepts cluster.
    groups = OrderedDict()
    for col, entry in columns.items():
        target = commonized_name(col, renamed)
        key = target if target else "(unmapped — not in renamed_columns)"
        groups.setdefault(key, []).append((col, entry))

    lines.append("## Columns grouped by commonized name")
    lines.append("")
    for target, members in groups.items():
        in_final = target in final_cols
        final_tag = " — **in `final_columns`** ✅" if in_final else ""
        lines.append(f"### `{target}`{final_tag}")
        lines.append("")
        lines.append("| raw column | # files | sample values |")
        lines.append("| --- | --- | --- |")
        for col, entry in members:
            vals = ", ".join(f"`{v}`" for v in list(entry["values"])[:12])
            lines.append(f"| `{col}` | {len(entry['files'])} | {vals} |")
        lines.append("")

    # Files the pipeline filter drops (station rosters, excluded_filenames, odd archives).
    # Kept here so mis-exclusions stay visible (this is how we caught the 2018 underscore gap).
    if ignored_files:
        lines.append("## Files not fed to the pipeline")
        lines.append("")
        lines.append(
            "Excluded by `file_matcher` / `excluded_filenames`; their columns are NOT in the "
            "analysis above:"
        )
        lines.append("")
        for basename, header in ignored_files:
            lines.append(f"- `{basename}` — columns: {', '.join(header)}")
        lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("city")
    parser.add_argument("--rows", type=int, default=200, help="rows sampled per file")
    parser.add_argument(
        "--distinct", type=int, default=40, help="max distinct values kept per column"
    )
    parser.add_argument("--out", default=None, help="output markdown path")
    args = parser.parse_args()

    config, columns, renamed, final_cols, ignored, all_files, matched_files = (
        build_inventory(args.city, args.rows, args.distinct)
    )
    md = render_markdown(
        args.city, config, columns, renamed, final_cols, ignored, all_files, matched_files
    )

    out = args.out or os.path.join(
        REPO_ROOT, "doc", "column_inventory", f"{args.city}.md"
    )
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(md + "\n")
    print(f"Wrote {out}")
    print(
        f"  {len(all_files)} raw files, {len(matched_files)} pipeline-fed, "
        f"{len(columns)} distinct columns"
    )


if __name__ == "__main__":
    main()
