"""Inventory raw column names and sample values for a city.

Goal: surface every column that appears in a city's raw/ files (across schema
eras), grouped by the commonized name it maps to, together with a handful of
sample values per raw column. This makes it easy to decide which additional
columns are worth carrying into the parquet and which raw variants across
cities encode the same concept (so they can share one output column name).

Usage:
    poetry run python scripts/inventory_raw_columns.py boston
    poetry run python scripts/inventory_raw_columns.py boston --rows 200 --distinct 40
"""

import argparse
import csv
import gzip
import io
import os
from collections import OrderedDict

from citybikeshare.config.loader import load_city_config
from citybikeshare.utils.paths import get_csv_files

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def open_text(path):
    """Open a raw file transparently whether gzipped or plain."""
    if path.endswith(".gz"):
        return io.TextIOWrapper(gzip.open(path, "rb"), encoding="utf-8", errors="replace")
    return open(path, "rt", encoding="utf-8", errors="replace")


def file_matches(basename, matchers):
    """Does this file feed the trip pipeline (per config file_matcher)?"""
    if not matchers:
        return True
    return any(word in basename for word in matchers)


def sample_file(path, max_rows, max_distinct):
    """Return (header, {column: OrderedDict of distinct sample values}) for one file."""
    with open_text(path) as fh:
        reader = csv.reader(fh)
        try:
            header = next(reader)
        except StopIteration:
            return [], {}
        header = [h.strip() for h in header]
        samples = {col: OrderedDict() for col in header}
        for i, row in enumerate(reader):
            if i >= max_rows:
                break
            for col, val in zip(header, row):
                val = val.strip()
                if val == "":
                    continue
                bucket = samples[col]
                if val not in bucket and len(bucket) < max_distinct:
                    bucket[val] = None
        return header, samples


def build_inventory(city, max_rows, max_distinct):
    config = load_city_config(city)
    matchers = config.get("file_matcher")
    renamed = config.get("renamed_columns", {}) or {}
    final_cols = config.get("final_columns", []) or []

    raw_dir = os.path.join(REPO_ROOT, "data", city, "raw")
    files = sorted(get_csv_files(raw_dir))

    # column -> {"files": [basenames], "matched": bool, "values": OrderedDict}
    columns = OrderedDict()
    unmatched_files = []

    for path in files:
        basename = os.path.basename(path)
        matched = file_matches(basename, matchers)
        header, samples = sample_file(path, max_rows, max_distinct)
        if not matched:
            unmatched_files.append((basename, header))
        for col in header:
            entry = columns.setdefault(
                col, {"files": [], "matched": False, "values": OrderedDict()}
            )
            entry["files"].append(basename)
            entry["matched"] = entry["matched"] or matched
            for val in samples.get(col, {}):
                if val not in entry["values"] and len(entry["values"]) < max_distinct:
                    entry["values"][val] = None

    return config, columns, renamed, final_cols, unmatched_files, files


def commonized_name(col, renamed):
    return renamed.get(col, "")


def render_markdown(city, config, columns, renamed, final_cols, unmatched_files, files):
    lines = []
    lines.append(f"# Raw column inventory — {city}")
    lines.append("")
    lines.append(
        "Auto-generated by `scripts/inventory_raw_columns.py`. Lists every column "
        "found in `data/{city}/raw/`, the commonized name it maps to via "
        "`renamed_columns`, and sample distinct values.".replace("{city}", city)
    )
    lines.append("")
    lines.append(f"- Raw files scanned: **{len(files)}**")
    lines.append(f"- Distinct raw column names: **{len(columns)}**")
    lines.append(f"- `file_matcher`: `{config.get('file_matcher')}`")
    lines.append("")

    # Group raw columns by the commonized target so shared concepts cluster.
    groups = OrderedDict()
    for col, entry in columns.items():
        target = commonized_name(col, renamed)
        key = target if target else "(unmapped — not in renamed_columns)"
        groups.setdefault(key, []).append((col, entry))

    lines.append("## Columns grouped by commonized name")
    lines.append("")
    for target, members in groups.items():
        in_final = target in final_cols
        final_tag = " — **in `final_columns`** ✅" if in_final else ""
        lines.append(f"### `{target}`{final_tag}")
        lines.append("")
        lines.append("| raw column | in matched files? | # files | sample values |")
        lines.append("| --- | --- | --- | --- |")
        for col, entry in members:
            vals = ", ".join(f"`{v}`" for v in list(entry["values"])[:12])
            matched = "yes" if entry["matched"] else "no (ignored)"
            lines.append(
                f"| `{col}` | {matched} | {len(entry['files'])} | {vals} |"
            )
        lines.append("")

    # Files that don't match file_matcher (station rosters, odd archives) — these
    # never reach the parquet but their columns are shown above tagged "ignored".
    if unmatched_files:
        lines.append("## Files ignored by `file_matcher`")
        lines.append("")
        lines.append("These raw files exist but do not feed the trip pipeline:")
        lines.append("")
        for basename, header in unmatched_files:
            lines.append(f"- `{basename}` — columns: {', '.join(header)}")
        lines.append("")

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("city")
    parser.add_argument("--rows", type=int, default=200, help="rows sampled per file")
    parser.add_argument(
        "--distinct", type=int, default=40, help="max distinct values kept per column"
    )
    parser.add_argument("--out", default=None, help="output markdown path")
    args = parser.parse_args()

    config, columns, renamed, final_cols, unmatched, files = build_inventory(
        args.city, args.rows, args.distinct
    )
    md = render_markdown(args.city, config, columns, renamed, final_cols, unmatched, files)

    out = args.out or os.path.join(
        REPO_ROOT, "doc", "column_inventory", f"{args.city}.md"
    )
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(md + "\n")
    print(f"Wrote {out}")
    print(f"  files scanned: {len(files)}, distinct columns: {len(columns)}")


if __name__ == "__main__":
    main()
